theme: jekyll-theme-cayman
title: Spotify Playlist Data Analysis
description: Keeping Italian Olives Pure!
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
